### ISSUE TITLE
Spacing and Formatting Needs to be Fixed on Footer Icons

### ISSUE THREAD

**Issue by aardzark** [aardzark/Portfolio_Web_App#1]
1. The mobile or small view of the footer needs to be corrected so that the icons are evenly spaced vertically between the bottom of the page and the copyright text and not hugging the bottom of the page.
2. The non-mobile or >small view needs to be corrected so that the copyright text is centered vertically so that it is at the same height as the icons.
3. On the >small view the copyright text should be left-aligned and the icons should be right-aligned. On the <=small view the copyright text and icons should be centered.

**Comment by RohitChauhan98** [comment]
Hey! I can do it Please assign it to me

**Comment by aardzark** [comment]
> Hey! I can do it Please assign it to me

I just saw this message now. I actually spent all day addressing this and after several hours figured out an implementation for styling the footer contents using Bootstrap classes. 

However, I'll leave my solution in `1-fix-footer-css` and not merge it to `master` so that you can either come up with a implementation of your own independent of mine for educational purposes or improve my implementation further. A good place to start if you choose the latter may be to remove the reliance on the use of inline margins in a few of the elements but don't feel pressed to choose that option. I'll likely approve a pull request from you either way.
